// Bandhemsidor från danslogen.se — uppdateras med scrape-band-links.mjs
const BAND_LINKS = {
  "Ajax": "https://www.ajaxorkester.com/",
  "Allstars": "https://allstarsband.se/",
  "Anders & Sylve": "https://anders-sylve.business.site/",
  "Ankies": "http://www.ankies.se",
  "Arvingarna": "http://www.arvingarna.nu/",
  "Bakkens duo": "https://bakkensduo.webnode.se/",
  "Bandet": "http://bandet.nu/",
  "Basset": "http://www.basset.nu/",
  "Bjørns orkester": "http://www.bjornsorkester.no/",
  "Black Jack": "http://blackjackband.se/",
  "Blender": "http://www.blender.se/",
  "Bo Beverlöv": "http://bobeverlov.se/",
  "Bob Stevens": "http://www.bobstevens.se/",
  "Brogrens": "https://www.brogrensdansband.se/",
  "Callinaz": "http://www.callinaz.se/",
  "Callisto": "http://www.callisto-music.se/",
  "Camell Duo": "http://www.camell.se/",
  "Carisma": "http://www.carisma-musik.com/",
  "Casanovas": "http://www.casanovas.se/",
  "Cavaliers": "https://cavaliers.se/",
  "Cedrix": "http://www.cedrix.se/",
  "Christer Borg": "http://www.christerborg.nu/",
  "Christerz": "https://www.christerz.se/",
  "Cool Candys": "http://www.coolcandys.se/",
  "Cristina Taube med Pelle Olssons orkester": "http://www.musika.se/",
  "Damorkeztern med z": "http://www.damorkeztern.com/",
  "Danne Stråhed & Dynamo": "http://www.dannestrahed.se/",
  "Dansbolaget": "http://www.dansbolaget.se/",
  "Dansdax (FIN)": "https://www.dansdax.com/",
  "Dansebandet (N)": "http://www.dansebandet.no",
  "Danzerz": "http://www.danzerz.se/",
  "Date": "https://d8.nu/",
  "Diffraktionsbandet": "http://www.diffraktionsbandet.se/",
  "Donnez": "http://www.donnez.se/",
  "Dubbelt Upp": "http://www.dubbelt-upp.se",
  "Duo Comix": "http://www.duo-comix.com/",
  "Duo Vi": "http://bluenotemusic.se/",
  "Edwings": "https://edwings.n.nu/",
  "Ekdal Big Red": "https://www.ekdalbigred.se/",
  "Eklöfs": "http://www.eklofs.com/",
  "Eloge": "http://www.elogeorkester.se/",
  "Emilio Walter": "https://www.emiliowalter.com/?fbclid=IwAR1rWQifqRIP09XGCMOEC4GCv8eRNI9DXkuIfEXDmqvSUvS9xUmcFulBNzs",
  "Engdahls": "http://engdahls.info/",
  "Enjoy": "http://www.enjoymusic.nu/",
  "Erik Lihm": "http://www.eriklihm.se/",
  "Erik Lihm Duo": "http://www.eriklihm.se/",
  "Excess": "http://www.excess.se/",
  "Expanders": "http://www.expanders.se/",
  "Express (N)": "http://www.express.yt/",
  "Extas": "http://www.extas.se",
  "Extract": "http://www.extract.se/",
  "Ezcape": "https://dansbandetezcape.se/",
  "Fernandoz": "http://fernandoz.se/",
  "Freqvens": "http://www.freqvens.se",
  "Gideons": "http://www.gideons.se",
  "Glads": "http://www.glads.se/",
  "Guns Rosor": "https://gunsrosor.n.nu/",
  "Hanne Mette Band (N)": "http://www.hannemette.com/",
  "Hardes Big Band": "http://www.hardes.se/",
  "Hebbez": "https://www.d2hebbez.com/",
  "Hedenskogs": "http://andreashedenskog.se/",
  "Herrgårds": "https://herrgardsmusik.se/weare/weare.html",
  "Highlights": "http://www.bandethighlights.se/",
  "Holidays": "http://www.holidaysorkester.com/",
  "Högtryck (Åland)": "http://www.hogtryck.ax",
  "Icaros": "http://www.icarosdansorkester.com/",
  "Ingez": "http://www.ingez.se/",
  "Ingvar Fahsts": "https://ingvarfahsts.n.nu/?fbclid=IwAR2CFAZ3zLHsMT7UWmslz4tF96_IT9bfTCl7dEYyg9WXYHsg6R1ee_fT2jQ",
  "Jackpots": "http://www.jackpots-dansband.se/",
  "Jag & Du": "https://www.jagochdu.nu/",
  "Janne Martins": "http://www.jannemartins.se/",
  "JazzMaTazz": "http://www.jazzmatazz.se/",
  "Jogges": "http://www.joggesmusik.com/",
  "Jompaz": "https://www.jompaz.se",
  "Junix": "http://www.junix.se/",
  "Jönköpings storband": "http://www.jonkopingsstorband.se/",
  "Kandis (DK)": "http://www.kandis.dk",
  "Kapten P": "https://coverbandetkaptenp.wixsite.com/kaptenp",
  "Kenneth & Classe": "http://www.kennethoclasse.se",
  "Kjell & Kenneth": "http://www.mognaman.se/",
  "Kjelles Danskavalkad": "https://kjelles.com/",
  "Kjellez": "http://www.kjellez.se/",
  "Kollijox": "http://www.kollijox.se/",
  "Larz Kristerz": "http://www.larzkristerz.com",
  "Lasse Sigfridsson": "http://www.lassesigfridsson.se",
  "Lasse Stefanz": "http://www.lassestefanz.se/",
  "Lill-Arnes": "http://www.lill-arnes.se/",
  "Linköpings storband": "https://linkopingsstorband.nu/",
  "Looking Back Band": "https://lookingbackband.se/",
  "Mac Barons": "https://macbarons.blogspot.com/",
  "Mac Thonyz": "http://www.macthonyz.se/",
  "Magnus Carlsson": "http://www.magnusonline.se/",
  "Martinez": "http://www.martinez.se/",
  "Matz Bladhs": "http://www.matz-bladhs.se/",
  "Matz Rogers": "http://www.matzrogers.se/",
  "Micke Ahlgrens": "http://www.mickeahlgrens.se/",
  "Micke Wez": "http://www.mickewez.se/",
  "Mogna Män": "http://www.mognaman.se/",
  "Nacka Big Band": "http://www.nackabigband.com",
  "New Generation": "http://www.newgeneration.se/",
  "Nickez": "http://www.nickez.se",
  "Nickis": "https://soundcloud.com/nickisorkester-1?fbclid=IwAR0ypJiKQjDHpOCzZUHf-0ONtQj8whJR3g8ubRx48xXUuhguZ2_UzCUSwhs",
  "Nordhs": "http://nordhsorkester.se/",
  "Nyströms": "http://www.nystromsband.se/",
  "Ola & Jag": "http://www.olaojag.se/",
  "Ole Ivars (N)": "http://www.ole-ivars.no/",
  "One58": "https://one58blog.wordpress.com/?fbclid=IwAR2xYlOCxKiU78xGR-5_fVekWpyJ26Syf8PWlsqHo-NPvR3RpxNdmq3JS_A",
  "Pallez": "http://www.pallez.se/",
  "Patrick Eklöf": "http://www.eklofs.com/eklof.html",
  "Perikles": "http://www.perikles.se/",
  "PHs": "https://www.perhakans.se/",
  "Pia Pihlgrens": "http://www.piapihlgrens.se/",
  "PK & Dansefolket (N)": "https://www.pkdf.no/",
  "Remlenz": "https://www.remlenz.com/",
  "Rent drag": "http://www.rentdrag.se",
  "Replay (FIN)": "http://replay-music.fi/",
  "Rignells": "https://rignells.se/",
  "Rixons": "http://www.rixons.se/",
  "Robert Nilssons Orkester": "https://www.rnorkester.se/",
  "Rogge Roll Duo": "https://www.youtube.com/watch?v=mwdi2V0wtI4",
  "Rose-Maries": "http://www.rosemaries.nu/",
  "Rune Rudberg Band (N)": "http://www.runerudbergband.no/",
  "Sandbypågarna": "https://sandbypagarna.webnode.se/",
  "Sanders (N)": "https://sanders.no/",
  "Sandins": "https://www.sandins.nu/",
  "Sandraz": "https://sandraz.se/",
  "Sannex": "http://www.sannex.nu/",
  "Scotts": "http://www.scotts.nu/",
  "Shine": "http://bandetshine.se/",
  "Sinitaivas": "https://sinitaivas.com/",
  "Sjögren & Company": "https://www.sjogrenocompany.se",
  "Sounders": "http://www.sounders.se/",
  "Special  Delivery Storband": "http://www.stefananderssonmusic.com/ensembler/specialdelivery.html",
  "Spotlight": "http://www.spotlightorkester.se/",
  "Stefans 2.0": "https://stefans2point0.fanlink.to/stefans2point0",
  "Sten & Stanley": "http://www.stenochstanley.se/",
  "Stig Sandberg": "https://www.stigsandberg.se/",
  "Streaplers": "http://www.streaplers.se/",
  "Strike": "https://www.strikeorkester.se",
  "Sunrise": "http://www.sunriseorkester.nu/",
  "Sven-Gunnars": "http://www.dansmusik.n.nu/sven-gunnars",
  "Svenne och Jörgen": "https://www.xn--svennejrgen-xfb.se/",
  "Sweedz": "http://www.mm-musik.se/",
  "Thor Görans": "http://www.thorgorans.com/",
  "Titanix": "http://www.titanix.se",
  "Tomas Fantz (FIN)": "http://tomasfantz.fi/",
  "Tomaz & Co": "http://www.tomaz.se/",
  "Tommys": "http://www.tommys-musik.fi",
  "Trebello": "http://www.trebello.se/",
  "Trendix": "http://trendixorkester.se/",
  "Tyttiz": "http://www.tyttiz.se/tyttiz-12495897",
  "Uppland Big Band": "http://www.upplandbigband.se/",
  "Vikingarna": "https://www.vikingarna.eu",
  "Voize": "http://www.voize.se",
  "Watts Up": "https://www.wattsup.se/",
  "Whispering Band": "http://www.whisperingband.se/",
  "Wickys": "http://www.wickys.se/",
  "Wåxbos": "http://www.waxbos.se",
  "Xplays": "http://www.xplays.se"
};
